"""Generate rouage/CONFORMANCE.md - the record that the two trains agree.

Le Rouage routes twice: rouage.py in Python, train.js in the browser. That
duplication is the cost of an interactive dial, and it is survivable on two
conditions, both mechanical - no gate vocabulary in JS, and the engines shown
to agree rather than asserted to.

test_conformance.py is where the showing happens. This is where the result is
written down, because a suite that passes on someone's laptop and is never
recorded proves nothing to the next reader. The file it emits is regenerated
and diffed in CI, so a record that has drifted from the engines it describes
is a test failure rather than a stale document nobody reopened.

    python3 rouage/conformance.py            write CONFORMANCE.md
    python3 rouage/conformance.py --check    exit 1 if the committed file is stale
    python3 rouage/conformance.py --stdout   print, write nothing

Node is required. Without it only half the claim can be checked, and a record
that said "the engines agree" having run one engine would be exactly the kind
of unearned claim the instrument is built against.
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

import emit
from rouage import load_ring, route
from test_conformance import (ARMED, UTTERANCES, js_proposal_traces, js_traces,
                              proposal_cases, roles, verifier_for)

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
OUT = HERE / "CONFORMANCE.md"

BANNER = "<!-- GENERATED by rouage/conformance.py. Do not edit this file. -->"

# What the record fingerprints. A conformance claim is about specific engines
# reading a specific doctrine; naming them by content is what stops the record
# outliving the thing it describes.
FINGERPRINTED = (
    ("Python train", "rouage/rouage.py"),
    ("Browser train", "rouage/train.js"),
    ("Barrel seam", "rouage/barillet.py"),
    ("Doctrine -> JSON", "rouage/emit.py"),
    ("The manifest", "overlays/le-conseil.md"),
)


def fingerprint(rel: str) -> str:
    return hashlib.sha256((REPO / rel).read_bytes()).hexdigest()[:16]


def literal_half(ring):
    """Every utterance x armed state, both engines, compared field by field."""
    cases = [(u, a) for u in UTTERANCES for a in ARMED]
    js = js_traces(cases)
    disagreements = []
    for (u, a), j in zip(cases, js):
        p = route(ring, u, a).to_dict()
        same = (
            [(x["position"], x["state"], x["reason"]) for x in p["positions"]]
            == [(x["position"], x["state"], x["reason"]) for x in j["positions"]]
            and p["failures"] == j["failures"]
            and p["notices"] == j["notices"]
            and p["stages"] == j["stages"]
            and p["admitted"] == j["admitted"]
            and p["route"] == j["route"]
            and p["route_end"] == j["routeEnd"]
        )
        if not same:
            disagreements.append(f"{u!r} armed={a}")
    return cases, disagreements


def barrel_half(ring):
    """Every branch of the Cited admission policy, both engines."""
    cases = proposal_cases(ring)
    js = js_proposal_traces(cases)
    rows, disagreements = [], []
    for c, j in zip(cases, js):
        p = route(ring, c["utterance"], c["armed"],
                  proposals=[tuple(x) for x in c["proposals"]],
                  verify=verifier_for(c["resolvable"]),
                  require_evidence=c["requireEvidence"]).to_dict()

        same = (
            [(x["position"], x["state"], x["reason"], x["note"])
             for x in p["positions"]]
            == [(x["position"], x["state"], x["reason"], x["note"])
                for x in j["positions"]]
            and p["failures"] == j["failures"]
            and p["notices"] == j["notices"]
            and p["stages"] == j["stages"]
            and p["admitted"] == j["admitted"]
        )
        if not same:
            disagreements.append(c["name"])

        admitted = [x for x in p["positions"]
                    if x["reason"].startswith("proposed:") and x["state"] == "active"]
        sealed = [x for x in p["positions"]
                  if x["reason"].startswith("proposed:") and x["state"] == "sealed"]
        if admitted:
            outcome = f"admitted ({len(admitted)})"
        elif sealed:
            outcome = "held sealed"
        elif p["failures"]:
            outcome = "rejected"
        else:
            outcome = "no change"
        detail = p["failures"][0] if p["failures"] else (
            admitted[0]["note"] if admitted and admitted[0]["note"] else "—")
        detail = detail.replace("rejected proposal: ", "")
        if len(detail) > 96:
            detail = detail[:93] + "..."
        rows.append((c["name"], outcome, detail, "agree" if same else "DIVERGE"))
    return cases, rows, disagreements


def render() -> str:
    if not shutil.which("node"):
        raise SystemExit(
            "conformance: node is required. Half a conformance run is not a "
            "conformance record.")

    ring = load_ring()
    lit_cases, lit_bad = literal_half(ring)
    bar_cases, rows, bar_bad = barrel_half(ring)
    sealed, prohibited, plain = roles(ring)

    node_version = subprocess.run(["node", "--version"], capture_output=True,
                                  text=True).stdout.strip()

    branches = {
        "unknown member": "unknown member",
        "cited a prohibition": "prohibition offered as grounds",
        "cited text not found": "citation not verbatim",
        "does not resolve": "evidence that does not resolve",
        "supplied no evidence": "evidence required, none given",
    }
    covered = {label: False for label in branches.values()}
    for _, _, detail, _ in rows:
        for needle, label in branches.items():
            if needle in detail:
                covered[label] = True

    L = []
    add = L.append
    add("# LE ROUAGE — CONFORMANCE")
    add("")
    add(BANNER)
    add("<!-- Regenerate: python3 rouage/conformance.py -->")
    add("")
    add("**The train decides nothing — and it decides nothing twice.**")
    add("")
    add("Le Rouage routes in two places. `rouage/rouage.py` is the train; "
        "`rouage/train.js` is the same train in the browser, because the "
        "interactive dial has to route without Python. That is a second "
        "implementation of the stage logic, which is exactly the duplication "
        "the rest of this build refuses — the roster, the ladder, the cap and "
        "every phrase are parsed from markdown precisely so nothing is written "
        "twice.")
    add("")
    add("It is survivable on two conditions, and both are mechanical:")
    add("")
    add("1. **No gate vocabulary in JS.** `emit.py` generates all of it from "
        "doctrine and ships it as data.")
    add("2. **The engines are shown to agree**, not asserted to. The same "
        "matrix runs through both and the traces are compared field by field.")
    add("")
    add("This file is the second condition, written down. It is generated by "
        "`rouage/conformance.py` from a live run of both engines and checked in "
        "CI, so it cannot describe a state the code is no longer in.")
    add("")
    add("## The engines")
    add("")
    add("| Part | Path | Fingerprint |")
    add("|---|---|---|")
    for label, rel in FINGERPRINTED:
        add(f"| {label} | `{rel}` | `{fingerprint(rel)}` |")
    add("")
    add(f"Browser engine executed under `{node_version}`. Fingerprints are the "
        "first 16 hex of the file's SHA-256 — they identify what was actually "
        "run, so this record cannot outlive the engines it describes.")
    add("")
    add("## The literal half — stages 2 and 2b")
    add("")
    add(f"{len(lit_cases)} cases: {len(UTTERANCES)} utterances × "
        f"{len(ARMED)} arming states. Phrase matching, named routes, the cap, "
        "the seal, and where each route actually ended.")
    add("")
    if lit_bad:
        add("**DIVERGENCE:** " + "; ".join(lit_bad))
    else:
        add(f"**All {len(lit_cases)} agree** — positions, states, reasons, "
            "failures, notices, stages, precedence order and route readings.")
    add("")
    add("## The barrel's half — stage 6, COLLECT")
    add("")
    add("The stage the train cannot perform. A prose activation bullet — "
        "*\"an artifact shows modification whose cause is unknown\"* — is not "
        "matchable without reading for meaning, and the train is forbidden "
        "that reading. So the barrel proposes and the train disposes: a "
        "proposal is admitted only if its citation is **verbatim** one of that "
        "member's own Activation bullets, which is still a literal string "
        "match. Whatever read the artifact and decided the bullet applied was "
        "the barrel, upstream.")
    add("")
    add("Until this record existed, `train.js` implemented the literal half "
        "only. `emit.py` had shipped `bullets` and `prohibitions` to the "
        "browser all along, against the day the browser would need them — so a "
        "proposal admitted in Python was a council state the dial could not "
        "reproduce. Both engines now admit, and the matrix below is run "
        "through both.")
    add("")
    add(f"Roles are chosen by property, not by name — sealed: **{sealed.name}**, "
        f"carries prohibitions: **{prohibited.name}**, plain: **{plain.name}** — "
        "so a doctrine rename cannot leave a stale name in the matrix.")
    add("")
    add("| Case | Outcome | Detail | Engines |")
    add("|---|---|---|---|")
    for name, outcome, detail, verdict in rows:
        add(f"| {name} | {outcome} | {detail} | {verdict} |")
    add("")
    if bar_bad:
        add("**DIVERGENCE:** " + "; ".join(bar_bad))
    else:
        add(f"**All {len(bar_cases)} agree** — including every rejection "
            "string, which `train.js` duplicates by hand and this compares "
            "verbatim.")
    add("")
    add("### Branch coverage")
    add("")
    add("Every way a proposal can be refused, exercised:")
    add("")
    for label, hit in covered.items():
        add(f"- {'✓' if hit else '✗'} {label}")
    add("")
    add("A matrix that quietly stopped covering a branch would keep passing, "
        "so `test_the_matrix_actually_exercises_every_branch` asserts this set "
        "directly. And because two engines can agree perfectly by both doing "
        "nothing, `test_a_proposal_can_actually_convene_someone` checks the "
        "positive case on its own.")
    add("")
    add("## What this does not claim")
    add("")
    add("- **Not that a citation is true.** A verbatim citation proves the "
        "gate is real. It cannot prove the premise was: the barrel can quote a "
        "bullet perfectly with nothing having been modified at all. Evidence "
        "narrows that gap — an object id the train resolves without reading it "
        "— and narrowing is not closing. It catches fabrication, not "
        "misattribution.")
    add("- **Not that the barrel is correct.** Nothing here inspects the "
        "reading that produced a proposal. The train's claim is only that what "
        "it admitted, it admitted by rule, and that both engines applied the "
        "same rule to the same input.")
    add("- **Not that the dial is correct.** The engines agreeing is not the "
        "readouts agreeing; that is a separate seam with its own test.")
    add("")
    add("## Reproduce")
    add("")
    add("```sh")
    add("python3 -m unittest discover rouage -v   # both engines, every case")
    add("python3 rouage/conformance.py --check    # this record is not stale")
    add("```")
    add("")
    add("A thing documented is a thing not yet lost.")
    return "\n".join(L) + "\n"


def main(argv) -> int:
    text = render()
    if "--stdout" in argv:
        sys.stdout.write(text)
        return 0
    if "--check" in argv:
        if not OUT.exists():
            print("conformance: CONFORMANCE.md missing; run "
                  "`python3 rouage/conformance.py`", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print("conformance: CONFORMANCE.md is stale; regenerate with "
                  "`python3 rouage/conformance.py`", file=sys.stderr)
            return 1
        print("conformance: CONFORMANCE.md matches a live run of both engines")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
